
---
- hosts: all

  # Stores all output for each run in a created directory.
  # By default, this dir is created in current dir.
  # To change that, provide:
  # vars: 
  #   - run_basedir: /tmp (or whatever)

  tasks:
  - name: get current directory
    run_once: true
    local_action:
      module: command
      args: pwd
    register: run_cwd

  - name: set base directory
    set_fact:
      run_pdir: "{{ run_basedir | default(run_cwd.stdout) }}"

  - name: generate run timestamp
    run_once: true
    local_action:
      module: shell
      args: 'date +%F_%s'
    register: run_ts

  - name: set run directory
    set_fact:
      run_dir: '{{ run_pdir }}/run_{{ run_ts.stdout }}'

  - name: create run directory
    run_once: true
    local_action:
      module: file
      path: '{{ run_dir }}'
      state: directory

  - include_role:
      name: calm_fio_iops
    vars: 
      calm_fio_iops_mode: prepare
    when: calm_enabled is defined and calm_enabled

  - include_role:
      name: '{{ benchmark_name }}'
    vars: 
      benchmark_mode: prepare

  - include_role:
      name: collect_sysstat
    vars: 
      collect_sysstat_mode: start

  - include_role:
      name: calm_fio_iops
    vars: 
      calm_fio_iops_mode: run
    when: calm_enabled is defined and calm_enabled

  - include_role:
      name: '{{ benchmark_name }}'
    vars: 
      benchmark_mode: run

  - include_role:
      name: calm_fio_iops
    vars: 
      calm_fio_iops_mode: stop
    when: calm_enabled is defined and calm_enabled

  - include_role:
      name: collect_sysstat
    vars: 
      collect_sysstat_mode: stop

  - include_role:
      name: collect_sysstat
    vars: 
      collect_sysstat_mode: gather
      collect_sysstat_dir: '{{ run_dir }}'

  - include_role:
      name: calm_fio_iops
    vars: 
      calm_fio_iops_mode: gather
      calm_fio_iops_dir: '{{ run_dir }}'
    when: calm_enabled is defined and calm_enabled

  - include_role:
      name: get_sysinfo
    vars: 
      get_sysinfo_dir: '{{ run_dir }}'

...
