
---
- hosts: all

  # stores all output for each run in a created directory
  # by default, this dir is created in current dir
  # to change that, provide 
  # vars: 
  #   - run_basedir: /tmp (or whatever)

  tasks:
  - name: get current directory
    local_action:
      module: command
      args: pwd
    register: run_cwd

  - name: set base directory
    set_fact:
      run_pdir: "{{ run_basedir | default(run_cwd.stdout) }}"

  - name: generate run timestamp
    local_action:
      module: shell
      args: 'date +%F_%s'
    register: run_ts

  - name: set run directory
    set_fact:
      run_dir: '{{ run_pdir }}/run_{{ run_ts.stdout }}'

  - name: create run directory
    local_action:
      module: file
      path: '{{ run_dir }}'
      state: directory

