

---
# quickly test a particular benchmark (role)

- hosts: all

  tasks:

  - name: set run directory
    set_fact:
      run_dir: /tmp/run_ts

  - name: create run directory
    local_action:
      module: file
      path: '{{ run_dir }}'
      state: directory

  - include_role:
      name: fio_1client_randio
    vars:
      fio_1client_randio_resdir: '{{ run_dir }}'
      fio_1client_randio_client: '{{ groups.clients[0] }}'
      fio_1client_randio_servers: '{{ groups.servers }}'
...
