

---
# quickly test a particular benchmark (role)

- hosts: all

  tasks:

  - name: set run directory
    set_fact:
      run_dir: /tmp/run_ts

  - name: create run directory
    local_action:
      module: file
      path: '{{ run_dir }}'
      state: directory

  - include_role:
      name: calm_fio_iops
    vars:
      calm_fio_iops_mode: prepare

  - include_role:
      name: calm_fio_iops
    vars:
      calm_fio_iops_mode: run

  - pause:
      seconds: 300

  - include_role:
      name: calm_fio_iops
    vars:
      calm_fio_iops_mode: stop

  - include_role:
      name: calm_fio_iops
    vars:
      calm_fio_iops_mode: gather
      calm_fio_iops_resdir: '{{ run_dir }}'

...
