

---
# quickly test a particular benchmark (role)

- hosts: all

  tasks:

  - name: set run directory
    set_fact:
      run_dir: /tmp/run_ts

  - name: create run directory
    local_action:
      module: file
      path: '{{ run_dir }}'
      state: directory

  - include_role:
      name: '{{ benchmark_name }}'
    vars:
      benchmark_mode: prepare

  - include_role:
      name: '{{ benchmark_name }}'
    vars:
      benchmark_mode: run

...
