

---
# quickly test a particular benchmark (role)

- hosts: all

  tasks:

  - name: set run directory
    set_fact:
      run_dir: /tmp/run_ts

  - name: create run directory
    local_action:
      module: file
      path: '{{ run_dir }}'
      state: directory

  - include_role:
      name: smallfile_1client
    vars:
      smallfile_1client_resdir: '{{ run_dir }}'
      smallfile_1client_client: '{{ groups.clients[0] }}'
      smallfile_1client_servers: '{{ groups.servers }}'
...
