---
# tasks file for collect_sysstat

- include_tasks: start.yml
  when: collect_sysstat_mode == "start"

- include_tasks: stop.yml
  when: collect_sysstat_mode == "stop"

- include_tasks: gather.yml
  when: collect_sysstat_mode == "gather"

