---

- name: setup timestamps for tests in fio_1client_randio
  shell: 'echo "fio_1client_randio timestamps: " > /tmp/fio_1client_randio.ts.txt'
  when: inventory_hostname == fio_1client_randio_client

- name: mark start of seq write test
  shell: 'echo -n "starting seq write test: " >> /tmp/fio_1client_randio.ts.txt; date >> /tmp/fio_1client_randio.ts.txt'
  when: inventory_hostname == fio_1client_randio_client

- name: create fio sequential write job
  blockinfile:
    path: /tmp/fio_1client_randio.write.job
    create: yes
    block: |
      [initialwrite]
      ioengine=sync
      rw=write
      create_on_open=1
      end_fsync=1
      bs={{ fio_1client_randio_sbs_kb }}k
      directory={{ fio_1client_randio_mntpt }}
      filename_format=f.$jobnum.$filenum
      numjobs={{ fio_1client_randio_njobs }}
      filesize={{ fio_1client_randio_fsz_gb }}g
      size={{ fio_1client_randio_fsz_gb }}g
  when: inventory_hostname == fio_1client_randio_client

- name: fio sequential write
  shell: 'fio /tmp/fio_1client_randio.write.job --output=/tmp/fio_1client_randio.write.out.txt'
  when: inventory_hostname == fio_1client_randio_client

- name: mark end of write test
  shell: 'echo -n "write test done: " >> /tmp/fio_1client_randio.ts.txt; date >> /tmp/fio_1client_randio.ts.txt'
  when: inventory_hostname == fio_1client_randio_client

- include_role: 
    name: drop_caches
...
