---
# defaults file for smallfile_1client

# path for smallfile benchmark
smallfile_1client_binpath: '/root/benchmarks/smallfile/smallfile-master'

# path for smallfile benchmark
smallfile_bench: '{{ smallfile_1client_binpath }}/smallfile_cli.py'

# where test fs is mounted on the client
smallfile_1client_mntpt: /mnt/dfsmnt

# number of threads
smallfile_1client_nthrds: 2

# number of files per thread
smallfile_1client_nfiles: 8192

# file size
smallfile_1client_fsz_kb: 32

# select record size automatically
smallfile_1client_recsz_auto: true

# record size, if auto is not true
smallfile_1client_recsz_kb: 32

# files per directory 
smallfile_1client_dirsz: 100

# name to search for in find-name test
smallfile_1client_nametofind: "mtp.non_existent_name.non"

# size to search for in find-size test
smallfile_1client_sizetofind: "{{ smallfile_1client_fsz_kb|int * 2 }}"

# dest directory for output
smallfile_1client_resdir: '{{ run_dir }}'

# client hostname
smallfile_1client_client: '{{ groups.clients[0] }}'

# list of servers
smallfile_1client_servers: '{{ groups.servers }}'

...
