---
# tasks file for smallfile_1client

- name: setup directory structure
  file:
    path: '{{ smallfile_1client_mntpt }}/{{ item }}'
    state: directory
  loop:
    - created
    - tarred
    - untarred
  when: inventory_hostname == smallfile_1client_client

- name: setup timestamps for tests in smallfile_1client
  shell: 'echo "smallfile_1client timestamps: " > /tmp/smallfile_1client.ts.txt'
  when: inventory_hostname == smallfile_1client_client

- name: mark start of create test
  shell: 'echo -n "starting create test: " >> /tmp/smallfile_1client.ts.txt; date >> /tmp/smallfile_1client.ts.txt'
  when: inventory_hostname == smallfile_1client_client

- name: smallfile create
  shell: '{{ smallfile_bench }} --top {{ smallfile_1client_mntpt }}/created --threads {{ smallfile_1client_nthrds }} --files {{ smallfile_1client_nfiles }} --file-size {{ smallfile_1client_fsz_kb }} --record-size {{ smallfile_1client_recsz_kb }} --fsync y --operation create > /tmp/smallfile_1client.create.txt'
  when: inventory_hostname == smallfile_1client_client

- name: mark end of write test
  shell: 'echo -n "write test done:" >> /tmp/smallfile_1client.ts.txt; date >> /tmp/smallfile_1client.ts.txt'
  when: inventory_hostname == smallfile_1client_client

- name: drop client cache before smallfile read 
  shell: 'sync ; echo 3 > /proc/sys/vm/drop_caches'
  when: inventory_hostname == smallfile_1client_client

- name: drop server caches before smallfile read 
  shell: 'sync ; echo 3 > /proc/sys/vm/drop_caches'
  when: inventory_hostname in smallfile_1client_servers

- name: mark start of smallfile read
  shell: 'echo -n "starting read test:" >> /tmp/smallfile_1client.ts.txt; date >> /tmp/smallfile_1client.ts.txt'
  when: inventory_hostname == smallfile_1client_client


- name: collect smallfile output 
  fetch:
    src: "/tmp/smallfile_1client.{{ item }}"
    dest: '{{ smallfile_1client_resdir }}'
  loop:
    - ts.txt
    - create.txt
  when: inventory_hostname == smallfile_1client_client

