---
# defaults file for fio_1client_seqio---

# where distributed fs is mounted on the client
fio_1client_seqio_mntpt: /mnt/dfsmnt

# number of fio jobs
fio_1client_seqio_njobs: 2

# size of file written/read by each job
fio_1client_seqio_fsz_gb: 1

# block size for write/read
fio_1client_seqio_bs_kb: 128

# dest directory for output
fio_1client_seqio_resdir: '{{ run_dir }}'

# client hostname
fio_1client_seqio_client: '{{ groups.clients[0] }}'

# list of servers
fio_1client_seqio_servers: '{{ groups.servers }}'

...
