---
# tasks file for get_sysinfo

- name: capture system info
  block:
  - name: get_sysinfo cpuinfo
    shell: "cat /proc/cpuinfo > /tmp/get_sysinfo.cpuinfo.txt"
  - name: get_sysinfo meminfo
    shell: "cat /proc/meminfo > /tmp/get_sysinfo.meminfo.txt"
  - name: get_sysinfo lsblk
    shell: "lsblk > /tmp/get_sysinfo.lsblk.txt"
  - name: get_sysinfo df
    shell: "df -h > /tmp/get_sysinfo.df_h.txt"
  - name: get_sysinfo rpm list
    shell: "rpm -qa > /tmp/get_sysinfo.rpm_qa.txt"
    args:
      warn: no
  
- name: collect sys info
  fetch:
    src: "/tmp/get_sysinfo.{{ item }}.txt"
    dest: '{{ get_sysinfo_dir }}'
  loop:
    - cpuinfo
    - meminfo
    - lsblk
    - df_h
    - rpm_qa
...
