---
# tasks file for get_sysinfo

- name: capture system info
  block:
    shell: cat /proc/cpuinfo > /tmp/get_sysinfo.cpuinfo.txt
    shell: cat /proc/meminfo > /tmp/get_sysinfo.meminfo.txt
    shell: lsblk > /tmp/get_sysinfo.lsblk.txt
    shell: df -h > /tmp/get_sysinfo.df_h.txt
    shell: rpm -qa > /tmp/get_sysinfo.rpm_qa.txt
  
- name: collect sys info
  fetch:
    src: "/tmp/get_sysinfo.{{ item }}.txt"
    dest: '{{ get_sysinfo_dir }}'
  loop:
    - cpuinfo
    - meminfo
    - lsblk
    - df_h
    - rpm_qa
...
