---
# tasks file for get_sysinfo

- name: capture cpu info
  shell: cat /proc/cpuinfo > /tmp/get_sysinfo.cpuinfo.txt

- name: capture memory info
  shell: cat /proc/meminfo > /tmp/get_sysinfo.meminfo.txt

- name: capture block info
  shell: lsblk > /tmp/get_sysinfo.lsblk.txt

- name: capture df info
  shell: df -h > /tmp/get_sysinfo.df_h.txt
  
- name: collect sys info
  fetch:
    src: "/tmp/get_sysinfo.{{ item }}.txt"
    dest: '{{ get_sysinfo_dir }}'
  loop:
    - cpuinfo
    - meminfo
    - lsblk
    - df_h
...
